<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="t3" tests="1" failures="1" timestamp="17 Dec 2017 04:51:32 GMT" time="51.89" errors="0">
  <testcase name="DO" time="47.964" classname="com.tata.selenium.test.productProvisioningCases.TC_03_ProductProvisioningPopUpValidation">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.productProvisioningCases.TC_03_ProductProvisioningPopUpValidation.DO(TC_03_ProductProvisioningPopUpValidation.java:119)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- t3 -->
