<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="t5" tests="1" failures="1" timestamp="17 Dec 2017 03:23:36 GMT" time="129.53" errors="0">
  <testcase name="DO" time="126.684" classname="com.tata.selenium.test.inventoryNumberManagement.TC_04_Validating500Entries">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.inventoryNumberManagement.TC_04_Validating500Entries.DO(TC_04_Validating500Entries.java:142)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- t5 -->
