<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="t7" tests="1" failures="1" timestamp="17 Dec 2017 11:05:51 GMT" time="47.62" errors="0">
  <testcase name="DO" time="45.262" classname="com.tata.selenium.test.productPriceManagement.TC_06_UploadWithInvalidCost">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.productPriceManagement.TC_06_UploadWithInvalidCost.DO(TC_06_UploadWithInvalidCost.java:112)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- t7 -->
