<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="t7" tests="1" failures="1" timestamp="17 Dec 2017 03:43:39 GMT" time="47.099" errors="0">
  <testcase name="DO" time="45.323" classname="com.tata.selenium.test.inventoryNumberManagement.TC_05_ValidatingEndDateGreaterThanFrom">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.inventoryNumberManagement.TC_05_ValidatingEndDateGreaterThanFrom.DO(TC_05_ValidatingEndDateGreaterThanFrom.java:139)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- t7 -->
