<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="TC_04" tests="1" failures="1" timestamp="18 Dec 2017 05:27:07 GMT" time="86.235" errors="0">
  <testcase name="DO" time="82.706" classname="com.tata.selenium.test.customerPriceMgmtCases.TC_04_UploadCSVWithInvalidDate">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:272)
	at com.tata.selenium.test.customerPriceMgmtCases.TC_04_UploadCSVWithInvalidDate.DO(TC_04_UploadCSVWithInvalidDate.java:114)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- TC_04 -->
