<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="TC_10" tests="1" failures="1" timestamp="16 Dec 2017 18:00:41 GMT" time="36.717" errors="0">
  <testcase name="DO" time="34.817" classname="com.tata.selenium.test.supplierCostManagementCases.TC_08_UploadWithInvalidCostValue">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.supplierCostManagementCases.TC_08_UploadWithInvalidCostValue.DO(TC_08_UploadWithInvalidCostValue.java:116)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- TC_10 -->
