<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Executing Test Case -TC_04 -with TestdataId : Data_06]]>
    </line>
    <line>
      <![CDATA[ Url launch failed : java.net.MalformedURLException: For input string: "null"]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="3977" started-at="2017-07-19T11:57:39Z" finished-at="2017-07-19T11:57:43Z">
    <groups>
    </groups>
    <test name="TC_06" duration-ms="3977" started-at="2017-07-19T11:57:39Z" finished-at="2017-07-19T11:57:43Z">
      <class name="com.tata.selenium.test.deliveryStatistics.TC_04_SelectCustomerAccount">
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:com.tata.selenium.test.deliveryStatistics.TC_04_SelectCustomerAccount@517cd4b]" name="beforeMethod" is-config="true" duration-ms="130" started-at="2017-07-19T17:27:39Z" finished-at="2017-07-19T17:27:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC_04]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="DO(java.lang.String, java.lang.String)[pri:0, instance:com.tata.selenium.test.deliveryStatistics.TC_04_SelectCustomerAccount@517cd4b]" name="DO" duration-ms="3787" started-at="2017-07-19T17:27:39Z" finished-at="2017-07-19T17:27:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Data_06]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[TC_04]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error occured while launching the url -   java.net.MalformedURLException: For input string: "null"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error occured while launching the url -   java.net.MalformedURLException: For input string: "null"
	at org.testng.Assert.fail(Assert.java:93)
	at com.tata.selenium.utils.CommonUtils.LaunchUrl(CommonUtils.java:211)
	at com.tata.selenium.test.deliveryStatistics.TC_04_SelectCustomerAccount.DO(TC_04_SelectCustomerAccount.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Executing Test Case -TC_04 -with TestdataId : Data_06]]>
            </line>
            <line>
              <![CDATA[ Url launch failed : java.net.MalformedURLException: For input string: "null"]]>
            </line>
          </reporter-output>
        </test-method> <!-- DO -->
        <test-method status="FAIL" signature="afterMethod(java.lang.String)[pri:0, instance:com.tata.selenium.test.deliveryStatistics.TC_04_SelectCustomerAccount@517cd4b]" name="afterMethod" is-config="true" duration-ms="3" started-at="2017-07-19T17:27:43Z" finished-at="2017-07-19T17:27:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC_04]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.tata.selenium.test.deliveryStatistics.TC_04_SelectCustomerAccount.afterMethod(TC_04_SelectCustomerAccount.java:630)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:723)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.tata.selenium.test.deliveryStatistics.TC_04_SelectCustomerAccount -->
    </test> <!-- TC_06 -->
  </suite> <!-- Suite -->
</testng-results>
